version: '3.8'

services:
  fastapi:
    build: .
    command: /app/entrypoint.sh
    env_file:
      - .env
    depends_on:
      - redis
      - db
    ports:
      - "8001:8000"
    restart: always
    container_name: fastapi
    volumes:
      - ./src:/app/src
    networks:
      - service_network
    environment:
      - PYTHONPATH=/app/src

  redis:
    image: redis:7.4.2
    ports:
      - "6380:6379"
    container_name: redis_fastapi
    networks:
      - service_network

  celery:
    build: .
    command: /app/entrypoint-celery.sh
    env_file:
      - .env
    depends_on:
      - db
      - redis
    container_name: celery
    profiles:
      - celery
    volumes:
      - ./src:/app/src

  db:
    image: postgres:15
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_CONFIG__postgres_db}
      POSTGRES_USER: ${DB_CONFIG__postgres_user}
      POSTGRES_PASSWORD: ${DB_CONFIG__postgres_password}
    ports:
      - "5433:5432"
    networks:
      - service_network

networks:
  service_network:
    external: true
